version: '2'
services:
  kong-database:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    ports:
      - 5432:5432
  kong:
    image: koudaiii/kong
    environment:
      - DATABASE=postgres
      - POSTGRES_HOST=kong-database
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=kong
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=
      - CLUSTER_IP=
      - CLUSTER_PORT=
      - ADVERTISE_IP=
      - ADBERTISE_PORT=
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 7946:7946
      - 7946:7946/udp
    security_opt:
      - seccomp:unconfined
    links:
      - kong-database
