apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong
  namespace: kong
  labels:
    name: kong
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 5
  template:
    metadata:
      name: kong
      labels:
        name: kong
    spec:
      containers:
      - image: mashape/kong:0.9.0
        name: kong
        ports:
          - containerPort: 8000
            name: http
          - containerPort: 8443
            name: https
          - containerPort: 8001
            name: admin
          - containerPort: 7946
            name: cluster
          - containerPort: 7946
            protocol: UDP
            name: cluster-udp
        env:
          - name: KONG_LOG_LEVEL
            value: notice
          - name: KONG_PROXY_LISTEN
            value: 0.0.0.0:8000
          - name: KONG_PROXY_LISTEN_SSL
            value: 0.0.0.0:8443
          - name: KONG_ADMIN_LISTEN
            value: 0.0.0.0:8001
          - name: KONG_DATABASE
            value: postgres
          - name: KONG_PG_HOST
            valueFrom:
              secretKeyRef:
                name: kong
                key: postgres-host
          - name: KONG_PG_PORT
            valueFrom:
              secretKeyRef:
                name: kong
                key: postgres-port
          - name: KONG_PG_USER
            valueFrom:
              secretKeyRef:
                name: kong
                key: postgres-user
          - name: KONG_PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kong
                key: postgres-password
          - name: KONG_PG_DATABASE
            valueFrom:
              secretKeyRef:
                name: kong
                key: postgres-database
          - name: KONG_CLUSTER_LISTEN
            valueFrom:
              secretKeyRef:
                name: kong
                key: cluster-listen
          - name: KONG_CLUSTER_ADVERTISE
            valueFrom:
              secretKeyRef:
                name: kong
                key: cluster-advertise
          - name: KONG_CLUSTER_PROFILE
            value: wan
          - name: KONG_DNSMASQ
            value: 'off'
          - name: KONG_DNS_RESOLVER
            valueFrom:
              secretKeyRef:
                name: kong
                key: dns-ip
