apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong
  labels:
    name: kong
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      name: kong
      labels:
        name: kong
    spec:
      imagePullSecrets:
        - name: wantedlybotkey
      containers:
      - image: quay.io/wantedly/kong
        name: kong
        ports:
          - containerPort: 8000
            name: http
          - containerPort: 8443
            name: https
          - containerPort: 8001
            name: admin
          - containerPort: 7946
            name: cluster
          - containerPort: 7946
            protocol: UDP
            name: cluster-udp
        env:
          - name: DNS_RESOLVER
            valueFrom:
              secretKeyRef:
                name: kong
                key: dns-resolver
          - name: DNS_IP
            valueFrom:
              secretKeyRef:
                name: kong
                key: dns-ip
          - name: DNS_PORT
            valueFrom:
              secretKeyRef:
                name: kong
                key: dns-port
          - name: DNSMASQ_PORT
            valueFrom:
              secretKeyRef:
                name: kong
                key: dnsmasq-port
          - name: CLUSTER_IP
            valueFrom:
              secretKeyRef:
                name: kong
                key: cluster-ip
          - name: CLUSTER_PORT
            valueFrom:
              secretKeyRef:
                name: kong
                key: cluster-port
          - name: ADVERTISE_IP
            valueFrom:
              secretKeyRef:
                name: kong
                key: advertise-ip
          - name: ADBERTISE_PORT
            valueFrom:
              secretKeyRef:
                name: kong
                key: advertise-port
          - name: DATABASE
            valueFrom:
              secretKeyRef:
                name: kong
                key: database
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: kong
                key: postgres-host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: kong
                key: postgres-port
          - name: POSTGRES_DATABASE
            valueFrom:
              secretKeyRef:
                name: kong
                key: postgres-database
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: kong
                key: postgres-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kong
                key: postgres-password
