apiVersion: v1
kind: Service
metadata:
  name: kong-external
  labels:
    name: kong
spec:
  type: LoadBalancer
  ports:
    - name: proxy-listen
      port: 80
      targetPort: 8000
    - name: proxy-listen-ssl
      port: 443
      targetPort: 8443
  selector:
    name: kong
