apiVersion: v1
kind: Service
metadata:
  name: kong-external
  labels:
    name: kong
spec:
  type: LoadBalancer
  ports:
    - name: kong1
      port: 8000
      targetPort: 8000
    - name: kong2
      port: 8443
      targetPort: 8443
    - name: kong3
      port: 8001
      targetPort: 8001
  selector:
    name: kong
