apiVersion: v1
kind: Service
metadata:
  name: kong-internal
  namespace: kong
  labels:
    name: kong
spec:
  type: NodePort
  ports:
    - name: proxy-listen
      port: 80
      targetPort: 8000
    - name: proxy-listen-ssl
      port: 443
      targetPort: 8443
    - name: admin-api-listen
      port: 8001
      targetPort: 8001
  selector:
    name: kong
