apiVersion: v1
kind: Service
metadata:
  name: kong-external
  namespace: kong
  labels:
    name: kong
spec:
  type: LoadBalancer
  ports:
    - name: proxy-listen
      port: 443
      targetPort: 8000
  selector:
    name: kong
